name: 'Process Manifests'
description: 'Process manifests for input to matrix'
inputs:
  path:
    description: 'Location of manifest files'
    required: false
    default: './manifests'
outputs:
  targets:
    description: list of targets to build
  # rcp_matrix:
  #   description: 'matrix config for rcp firmware'
  ncp_matrix:
    description: 'matrix config for ncp firmware'
  ot_matrix:
    description: 'matrix config for openthread firmware'
runs:
  using: 'node20'
  main: 'dist/index.js'
